Avopkg: fixed bug with manifest, moved pack/extract commands to variables

diff --git a/avopkg.in b/avopkg.in
--- a/avopkg.in
+++ b/avopkg.in
@@ -22,6 +22,9 @@ PYTHON_ENABLED="@ENABLE_PYTHON@"
 IS_UNIX="@UNIX@"
 IS_MAC="@APPLE@"
 
+PACK_CMD="tar czf"
+EXTRACT_CMD="tar xzf"
+
 # Helper functions
 
 # /**
@@ -86,7 +89,7 @@ then
     cp $2 .tmp/$package/$package.mf    
     cp -t .tmp/$package $files # Will fail if some file is missing
     cd .tmp
-    tar czf ../$package.avo $package
+    $PACK_CMD ../$package.avo $package
     cd ..
     rm -rf .tmp
     echo Done!
@@ -107,7 +110,7 @@ else
     rm -rf .tmp
     mkdir .tmp
     cd .tmp
-    tar xzf ../$1
+    $EXTRACT_CMD ../$1
     if ! test $? = 0
     then
         echo "$1 is not an Avogadro plugin package!"
@@ -117,16 +120,16 @@ else
 
     # Check manifest
     cd $package
-    pkg=$package
-    if ! test -f $pkg
+    manifest=$package.mf
+    if ! test -f $manifest
     then
-        echo "Manifest $pkg is missing in package!"
+        echo "Manifest $manifest is missing in package!"
         echo "Installation failed."
         exit 1
     fi
 
     # Find out where to install package
-    if ($(getBoolVar $pkg Python))
+    if ($(getBoolVar $manifest Python))
     then
         #Check Python support in Avogadro
         if test $PYTHON_ENABLED = "OFF"
@@ -143,14 +146,14 @@ else
         if test $USER = root
         then
             echo " for all users..."
-            dest="$PREFIX/share/libavogadro/$(getVar $pkg Category)Scripts"
+            dest="$PREFIX/share/libavogadro/$(getVar $manifest Category)Scripts"
         else
             echo " for user $USER"
-            if test $IS_MAC = 1
+            if test "$IS_MAC" = 1
             then
-                dest="$HOME/Library/Application Support/Avogadro/$(getVar $pkg Category)Scripts"
+                dest="$HOME/Library/Application Support/Avogadro/$(getVar $manifest Category)Scripts"
             else
-                dest="$HOME/.avogadro/$(getVar $pkg Category)Scripts"
+                dest="$HOME/.avogadro/$(getVar $manifest Category)Scripts"
             fi
         fi
     else       
@@ -158,14 +161,14 @@ else
         if test $USER = root
         then
             echo " for all users..."
-            dest="$PREFIX/$LIB_DIR/$PLUGIN_DIR/$(getVar $pkg Category)"
+            dest="$PREFIX/$LIB_DIR/$PLUGIN_DIR/$(getVar $manifest Category)"
         else
             echo " for user $USER"
-            if test $IS_MAC = 1
+            if test "$IS_MAC" = 1
             then
-                dest="$HOME/Library/Application Support/$PLUGIN_DIR/Plugins/$(getVar $pkg Category)"
+                dest="$HOME/Library/Application Support/$PLUGIN_DIR/Plugins/$(getVar $manifest Category)"
             else
-                dest="$HOME/.$PLUGIN_DIR/plugins/$(getVar $pkg Category)"
+                dest="$HOME/.$PLUGIN_DIR/plugins/$(getVar $manifest Category)"
             fi
         fi
     fi
@@ -177,7 +180,7 @@ else
         mkdir -p "$dest"
     fi
     echo "Copying files to $dest..."
-    cp -t "$dest" $(getMultiVar $pkg Files)
+    cp -t "$dest" $(getMultiVar $manifest Files)
 
     # Clean up
     cd ../..
