avopkg: Added ABI version check (ABI version hardcoded)
Added ABI version check for binary plugins.
Binary plugins for 1.x should not be normally used for 1.0.x, and vise versa
Python plugins are not affected by this change
Some whitespaces were removed
Change-Id:I6348c00b

diff --git a/avopkg.in b/avopkg.in
--- a/avopkg.in
+++ b/avopkg.in
@@ -28,6 +28,7 @@
   IS_MAC="@APPLE@"
   SYSTEM_NAME="@CMAKE_SYSTEM_NAME@"
   SIZEOF_VOID_P="@CMAKE_SIZEOF_VOID_P@"
+  ABI_VERSION="1.1"
 # ----- End of configured on Avogadro build ----- #
 
 # My name
@@ -309,11 +310,11 @@ then
                 exit 0
             fi
         fi
-    fi    
-    
+    fi
+
     echo -n "1. Full name of your plugin [$package]:"
     name=$(readString "$package")
-    
+
     echo -n "2. Author's name []:"
     author=$(readString "")
 
@@ -327,14 +328,14 @@ then
     if test "$python" = "y"
     then
         echo "Python" >> $manifest
-        
+
         echo -n "4. List of files to distribute [`ls *.py`]:"
         files=$(readString "`ls *.py`")
 
         echo "5. Choose a category for your Python plugin from list:"
         echo "* engineScripts\n* extensionScripts\n* toolScripts"
         category=$(readString "")
-    else    
+    else
         echo -n "4. List of files to distribute [`ls *.so`]:"
         files=$(readString "`ls *.so`")
 
@@ -529,7 +530,7 @@ then
         printUsage
         exit 255
     fi
-   
+
     package=$(getVar $2 Package)
     files="$(getMultiVar $2 Files)"
     rm -rf .tmp
@@ -548,6 +549,10 @@ then
         then
             echo "SizeofVoidP: $SIZEOF_VOID_P" >> .tmp/$package/$package.$MANIFEST_EXT
         fi
+        if test x$(getVar $2 AbiVersion) = x
+        then
+            echo "AbiVersion: $ABI_VERSION" >> .tmp/$package/$package.$MANIFEST_EXT
+        fi
     fi
 
     # Add version = 1 if missing
@@ -564,10 +569,10 @@ then
             $HASH_CMD $file >> .tmp/$package/$CHECKSUMS_FILE 2>/dev/null
         done
     fi
-        
+
     # Copy installable content
     cp -t .tmp/$package $files # Will fail if some file is missing
-    
+
     cd .tmp
     $PACK_CMD ../$package.$PKG_EXT $package
     cd ..
@@ -577,7 +582,7 @@ then
     exit 0
 else
             ########## Install package ########## 
-    
+
     # Check -f (ignore OS and arch)
     if test "$1" = "-f"
     then
@@ -621,7 +626,7 @@ else
         cleanupTmp
         exit 2
     fi
-        
+
     files=$(getMultiVar $manifest Files)
     category=$(getVar $manifest Category)
     reinstall=0 # 1- reinstall, 2- upgrade to newer
@@ -650,7 +655,7 @@ else
             fi
         fi
     fi
-    
+
     # Check for possible overwrites
     for file in $files
     do
@@ -675,7 +680,7 @@ else
                         "$0" -remove $package > /dev/null
                         reinstall=2
                     else
-                        echo "WARNING! Package $package is already installed."                    
+                        echo "WARNING! Package $package is already installed."               
                         reinstall=1
                     fi
                 else
@@ -714,7 +719,7 @@ else
             cleanupTmp
             exit 3
         fi
-        
+
         echo -n Installing Python plugin $package
         if test $USER = root
         then
@@ -735,7 +740,7 @@ else
                 cleanupTmp
                 exit 4
             fi
-    
+
             # Verify CPU architecture
             arch=$(getVar $manifest SizeofVoidP)
             if test $arch != $SIZEOF_VOID_P
@@ -760,8 +765,20 @@ else
                 cleanupTmp
                 exit 5
             fi
+
+            # Verify ABI version
+            abi=$(getVar $manifest AbiVersion)
+            if test $abi != $ABI_VERSION
+            then
+                echo "ABI version doesn't match"
+                echo "Required ABI version: $ABI_VERSION"
+                echo "ABI version of plugin: $abi"
+                echo "Installation failed"
+                cleanupTmp
+                exit 10
+            fi
         fi
-        
+
         echo -n Installing plugin $package
         if test $USER = root
         then
@@ -798,7 +815,7 @@ else
     # Clean up
     cd "$oldpwd"
     cleanupTmp
-    
+
     echo "Done!"
     exit 0
 fi
